[package]
name = "wiji"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
serde = { version = "1.0.214", features = ["derive"] }
serde_derive = "1.0.214"
serde_json = "1.0.132"
time = { version = "0.3.36", features = ["formatting", "local-offset", "macros", "parsing"] }
